# 5.16 List 2 Dimensi

List 2 dimensi adalah list yang didalamnya terdapat list lagi, sehingga ada list di dalam list. Apabila digambarkan seperti matriks, maka akan terdapat baris dan kolom. Sehingga list tersebut menjadi 2 dimensi.

### Contoh 1

In [3]:
##Mendeklarasikan list 2 dimensi        ##Struktur List 2 dimensi
matriks_44 = [                          ##nama_variabel_list = [
    [1, 2, 3, 4],                                ##[data_list1, data_list2, data_list3],
    [5, 6, 7, 8],                                ##[data_list4, data_list5, data_list6], 
    [9, 10, 11, 12],                             ##[data_list7, data_list8, data_list9]
    [13, 14, 15, 16]                    ##]
]

print(matriks_44)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


Struktur list matriks dari output di atas adalah:
[[baris1 index ke-0], [baris2 index ke-1], [baris3 index ke-2], [baris4 index ke-3]], dengan [[kolom1 index ke 0, kolom2 index ke 1, kolom3 index ke 2, kolom4 index ke 3]], dan begitu seterusnya.

Program di atas digunakan untuk menampilkan data list dalam bentuk matriks. Karena program di atas merupakan list 2 dimensi, sehingga terdapat baris dan kolom di dalamnya.

In [5]:
##Menampilkan matriks_44 dengan baris index ke-1

matriks_44[1]               ##nama_variabel_list[baris_dengan_index_yang_akan_ditampilkan]

[5, 6, 7, 8]

In [6]:
##Menampilkan matriks_44 dengan baris index ke-1 dan kolom index ke-2

matriks_44[1][2]           ##nama_variabel_list[baris][kolom]

7

In [8]:
##Mengubah isi data list matriks 

matriks_44[1][2] = 100     ##nama_variabel_list[baris][kolom] = data_baru
print(matriks_44[1][2])    ##print(nama_variabel_list[baris][kolom])

100


Program di atas digunakan untuk mengubah data dalam data list matriks pada baris dengan index ke 1 dan pada kolom dengan index ke 2, yang awal datanya adalah 7 diganti menjadi 100.

In [9]:
##Memanggil data list matriks_44

matriks_44

[[1, 2, 3, 4], [5, 6, 100, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Program di atas adalah data list matriks_44 yang sebelumnya sudah diubah datanya pada baris dengan index ke 1 dan pada kolom dengan index ke 2.

### Contoh 2

Penerapan List 2 Dimensi

In [12]:
##Looping untuk menampilkan data list matriks_44 menggunakan for loop

for baris_44 in matriks_44:        ##for <variabel> in <iterabel>
    print(baris_44)                      ##perintah
    for kolom_44 in baris_44:            ##for <variabel> in <iterabel>
        print(kolom_44)                        ##<perintah>

[1, 2, 3, 4]
1
2
3
4
[5, 6, 100, 8]
5
6
100
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


Pada program di atas akan dilakukan looping menggunakan for dalam for untuk menampilkan data list.

baris_44 digunakan untuk menampung data matriks_44 dalam perulangan, lalu setelah dilakukan perintah print(baris_44). Dilakukan for loop untuk manmpilkan data kolom_44 yang digunakan untuk menampung data baris_44. Jadi perulangan dalam for loop kedua dilakukan hanya sampai data baris_44 selesai, baru setelah itu program akan melakukan looping kembali ke for loop paling luar. Begitu seterusnya, hingga data dalam variabel list matriks_44 habis.

### Contoh 3

In [13]:
##Mendeklarasikan variabel data list
                                                 ##Struktur List 2 Dimensi
list_makanan_44 = [                              ##nama_variabel_list = [
    ['Bakso', 'Nasi Goreng', 'Pizza'],           ##      ['data_list1', 'data_list2', 'data_list3'],
    ['Nasi Uduk', 'Pecel', 'Ayam Geprek']        ##      ['data_list4', 'data_list5', 'data_list6']
]                                                ##]

##Menampilkan data list_makanan_44
print(list_makanan_44)

[['Bakso', 'Nasi Goreng', 'Pizza'], ['Nasi Uduk', 'Pecel', 'Ayam Geprek']]


In [15]:
##Looping untuk menampilkan data list_makanan_44 menggunakan for loop

for menu_44 in list_makanan_44:          ##for <variabel> in <iterabel>:
    for makanan_44 in menu_44:           ##    for <variabel> in <iterabel>:
        print(makanan_44)                ##          <perintah>

Bakso
Nasi Goreng
Pizza
Nasi Uduk
Pecel
Ayam Geprek


Program di atas dimulai dengan perulangan pada variabel menu_44 yang digunakan untuk menampung data list_makanan_44, lalu data nya akan melakukan perulangan dalam for loop kedua. Sehingga data tadi ada di dalam variabel menu_44, yang selanjutnya akan melakukan perulangan melalui variabel makanan_44 yang digunakan untuk menampung data dari menu_44. Setelah itu akan dijalankan perintah untuk melakukan print pada variabel makanan_44. Sehingga data yang ditampilkan akan ditampilkan ke bawah, karena terdapat for dalam for.

### Contoh 4

In [20]:
##Mendeklarasikan list vektor1_44 dan vektor2_44

vektor1_44 = [1, 2, 3, 4]
vektor2_44 = [5, 6, 7, 8]

In [18]:
##Mendeklarasikan list jumlah_vektor_44
jumlah_vektor_44 = [0, 0, 0, 0]

##Looping untuk melakukan penjumlahan list data
for isi_44 in range(len(vektor1_44)):
    jumlah_vektor_44[isi_44] = vektor1_44[isi_44] + vektor2_44[isi_44]
print(jumlah_vektor_44)

[6, 8, 10, 12]


Program di atas digunakan untuk menjumlahkan vektor1_44 dengan vektor2_44 yang datanya ditampung dalam jumlah_vektor_44. Untuk melakukan perulangan data, isi_44 akan menampung data dari panjang vektor1_44. Sehingga ketika dilakukan perulangan, perulangan tersebut akan terjadi sebanyak panjang dari vektor1_44. Lalu dilakukan perintah untuk melakukan penjumlahan pada data list 2 dimensi vektor1_44 dengan vektor2_44, yang hasil penjumlahannya akan ditampung/disimpan di variabel jumlah_vektor_44. Lalu setelah perulangan selesai, dilakukan print untuk menampilkan hasil dari penjumlahan diluar for loop.

# 5.17 Tuples

Tuples sama dengan list, hanya saja tuples datanya tidak dapat diubah. Jadi, tuples biasanya digunakan untuk penggunaan data yang isinya tidak akan diubah lagi. Apabila masih ingin melakukan pengubahan isi data, bisa menggunakan list saja.

In [22]:
##Deklarasikan variabel tuples
angka_44 = (0, 1, 1, 3, 4, 5) 

In [25]:
##Menampilkan data tuples angka_44 pada index ke 0
print(angka_44[0])

0


In [26]:
##Menampilkan data tuples angka_44 pada index ke 0 sampai 3 (data dengan index ke 3 tidak ikut ditampilkan, hanya sampai ke 2)
print(angka_44[0:3])

(0, 1, 1)


In [28]:
##Melakukan perulangan for untuk menampilkan data tuples angka_44 dari index ke 0 sampai index ke 3

for isi_44 in angka_44[0:3]:        ##for <variabel> in <iterabel>:
    print(isi_44)                   ##     <perintah>  

0
1
1


Program diatas melakukan perulangan dengan menyimpan data perulangan dalam variabel isi_44 yang digunakan untuk menampung data dari angka_44. Jadi yang melakukan perulangan for hanya data tuples dengan index ke 0 sampai index ke 3 saja.

In [29]:
##Mengubah data tuples angka_44 dengan index ke 0 menjadi 10
angka_44[0] = 10

TypeError: 'tuple' object does not support item assignment

Kode di atas error karena data tuples tidak dapat diubah. Sehingga terjadi error, dan tidak mengubah apapun

In [31]:
##Mengubah data tuples angka_44 dari belakang atau akhir
angka_44.append(10)

AttributeError: 'tuple' object has no attribute 'append'

Kode di atas error karena data tuples tidak dapat diubah dari depan maupun belakang. Sehingga terjadi error, dan tidak mengubah apapun

In [32]:
##Menghapus data tuples angka_44
angka_44.remove(5)

AttributeError: 'tuple' object has no attribute 'remove'

Kode di atas error karena data tuples tidak dapat diubah maupun dihapus. Sehingga terjadi error, dan tidak mengubah apapun

In [34]:
##Menghitung jumlah data menggunakan fungsi count
angka_44.count(1)                 ##nama_tuples.count(data_yang_ingin_dihitung)

2

Program di atas digunakan untuk menghitung jumlah data yang di panggil. Pada tuples angka_44 data 1 ada sebanyak 2. Sehingga outputnya = 2.

In [36]:
##Menampilkan tuples menggunakan fungsi index
angka_44.index(3)                 ##nama_tuples.index(data_yang_ingin_ditampilkan)

3

Program di atas digunakan untuk menampilkan atau memanggil data tuples dengan index ke 3. Sehingga outputnya = 3.

Kesimpulannya, data pada tuples tidak dapat ditambah maupun dihapus. Karena data tuples merupakan data tetap yang tidak dapat diubah.

# 5.18 Dictionaries

Dictionaries adalah tipe data pada Python yang digunakan untuk menyimpan kumpulan data dengan pendekatan "key-value". Komponen pada dictionary ada 2, yaitu key yang merupakan nama atribut suatu item pada dictionary, dan value yang merupakan nilai/data yang disimpan pada suatu atribut.

In [1]:
##Mendeklarasikan dictionary dengan 3 atribut(key)
                                                ##Struktur dictionary
data_orang_44 = {                               ##nama_dictionary = {
    'nama' : 'Alifa Fitriana Putri Yuaswan',    ##     'nama_atribut1' : 'data dalam atribut', disini bertipe data string
    'umur' : 20,                                ##     'nama_atribut2' : 'data dalam atribut', disini bertipe data int
    'apakah_singel' : True                      ##     'nama_atribut3' : 'data dalam atribut', disini bertipe data boolean
}

Note: Tipe data pada data dalam atribut bisa apa saja, tergantung apa yang diinginkan. Program di atas hanya contoh saja.

### Menampilkan data dalam Dictionary

In [2]:
##Menampilkan data dengan key/atribut 'nama'
print(data_orang_44['nama'])

Alifa Fitriana Putri Yuaswan


In [3]:
##Menampilkan data dengan key/atribut 'Nama'
print(data_orang_44['Nama'])

KeyError: 'Nama'

Kode di atas error karena key/atribut 'Nama' tidak ada dalam Dictionary, sehingga menjadi error. Ini merupakan case sensitif, sehingga besar kecilnya huruf harus diperhatikan.

### Mengambil data dalam atribut Dictionary

In [5]:
##Menampilkan data yang diambil dari atribut 'nama'
print(data_orang_44.get('nama'))

Alifa Fitriana Putri Yuaswan


In [6]:
##Menampilkan data yang diambil dari atribut 'Nama'
print(data_orang_44.get('Nama'))

None


Program di atas memiliki output none dikarenakan data dalam atribut yang akan diambil lalu ditampilkan tidak ada (disini terdapat kesahalahan dalam pemanggilan 'Nama', dimana atribut dengan 'Nama' itu tidak ada, yang ada hanya 'nama'), sehingga output menjadi none. Kembali lagi, ini case sensitif sehingga besar kecilnya huruf harus diperhatikan.

In [7]:
##Menampilkan data yang diambil dari atribut 'tanggal lahir'
print(data_orang_44.get('tanggal lahir'))

None


Program di atas outputnya none karena atribut 'tanggal lahir' tidak ada/tidak ditemukan.

In [9]:
##Menampilkan data yang diambil dari atribut 'tanggal lahir' dan data dalam atributnya '26-02-2012'
print(data_orang_44.get('tanggal lahir', '26-02-2012'))

26-02-2012


Mengapa data di atas tidak menghasilkan output none padahal tidak ada atribut 'tanggal lahir' pada dictionary? Hal itu disebabkan oleh kodenya. Di atas menunjukkan bahwa akan diambil data dari atribut 'tanggal lahir' yang isinya '26-02-2012', meskipun 'tanggal lahir' tidak ada dalam dictionary, tapi data tersebut akan tetap ditampilkan. Karena sudah dideklarasikan isi dari atributnya. Namun, data tersebut tidak akan tersimpan dalam dictionary, karena kode di atas digunakan hanya untuk mengambil lalu menampilkan data saja.

In [10]:
##Menampilkan isi dictionary data_orang_44
print(data_orang_44)

{'nama': 'Alifa Fitriana Putri Yuaswan', 'umur': 20, 'apakah_singel': True}


Atribut 'tanggal lahir' tidak ada dalam dictionary di atas karena atribut tersebut tidak ditambahkan sebelumnya.

In [11]:
##Menampilkan data dictionary dengan atribut 'tanggal lahir'
print(data_orang_44['tanggal lahir'])

KeyError: 'tanggal lahir'

Program di atas error karena atribut yang akan ditampilkan tidak ada/tidak ditemukan.

### Menambahkan atribut pada Dictionary

In [13]:
##Menambahkan atribut 'HP' pada dictionary data_orang_44
data_orang_44['HP'] = '081234567890'

In [14]:
##Menampilkan data dictionary dengan atribut 'HP'
print(data_orang_44['HP'])

081234567890


In [15]:
print(data_orang_44)

{'nama': 'Alifa Fitriana Putri Yuaswan', 'umur': 20, 'apakah_singel': True, 'HP': '081234567890'}


Atribut 'HP' berhasil ditambahkan dalam dictionary, sehingga ketika diberikan perintah print, dapat ditampilkan outputnya.

### Contoh 1

In [17]:
##Mendeklarasikan dictionary angka_44
angka_44 = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan'
}

In [18]:
##Digunakan untuk menyimpan data inputan nomor hp
nomor_hp_44 = input('Masukkan nomor HP anda : ')

##Digunakan untuk menyimpan data atribut angka_44 yang nanti dikonversi dalam bentuk kata
nomor_angka_44 = ' '

##Perulangan for digunakan untuk menampilkan dan mengambil data nomor_hp_44
for isi_44 in nomor_hp_44:                             ##for <variabel> in <iterabel>
    nomor_angka_44 += angka_44.get(isi_44) + ' '       ##   <perintah> = penambahan nomor_angka_44 dengan angka_44
                                                       ##                (dalam bentuk kata) + ' '
    
##Menampilkan hasil perulangan yang disimpan dalam variabel nomor_angka_44
print(nomor_angka_44)

Masukkan nomor HP anda : 081346869383
 nol delapan satu tiga empat enam delapan enam sembilan tiga delapan tiga 


Berdasarkan program di atas, akan ditampilkan sebuah konversi dari angka ke kata menggunakan dictionary dan for loop. Dimana dilakukan perulangan dengan isi_44 digunakan untuk menampung data inputan nomor_hp_44, lalu terjadi penambahan data atribut yang disimpan dalam variabel nomor_angka_44, karena terdapat kode angka_44.get(isi_44) maka data yang terambil dalam bentuk kata. Sehingga terjadi perulangan sesuai dengan jumlah inputan dari nomor_hp_44.

# 5.19 Fungsi dalam Python

Fungsi dalam Python adalah kumpulan perintah atau kode yang dikelompokkan menjadi satu agar bisa digunakan atau dipanggil berkali-kali. Adapun beberapa jenis fungsi pada Python yaitu, input, print, len, range, dan banyak fungsi lainnya.

In [26]:
##Mendeklarasikan fungsi
def full_name(first_name_44, last_name_44):                             ##def nama_fungsi(parameters1, parameters2):
    print(f'Nama lengkapnya adalah {first_name_44} {last_name_44}')     ##     perintah//statements    

In [27]:
##Mendeklarasikan parameters
first_name_44 = input('Nama depan anda adalah ')       ##parameters1
last_name_44 = input('Nama belakang anda adalah ')     ##parameters2

##Memanggil fungsi full_name
full_name(first_name_44, last_name_44)                 ##nama_fungsi(parameters1, parameters2)

Nama depan anda adalah Alifa
Nama belakang anda adalah Fitriana
Nama lengkapnya adalah Alifa Fitriana


Program di atas adalah tentang pembuatan fungsi yang memiliki 2 parameter. Fungsi di atas digunakan untuk memanggil nama lengkap dari data 2 parameter yang ada, yaitu first name dan last name.

## 5.19. 1 Tugas Fungsi pada Python

Akan dilakukan tugas fungsi pada python, yaitu menjalankan perintah dan menampilkan hasil perhitungan.

### Contoh 1

In [40]:
##Mendeklarasikan fungsi
def waktu_sampai(jarak_44, kecepatan_44):         ##def nama_fungsi(parameters1, parameters2):
    waktu_44 = jarak_44/kecepatan_44              ##     perintah/statments
    print(waktu_44)                               ##     perintah/statments

In [41]:
##Mendeklarasikan fungsi
def waktu_tempuh(jarak_44, kecepatan_44):         ##def nama_fungsi(parameters1, parameters2):
    waktu_44 = jarak_44/kecepatan_44              ##      perintah/statments
    return waktu_44                               ##      perintah/statments

In [30]:
##Memanggil fungsi waktu_sampai dengan parameter (100, 60)
waktu_sampai(100, 60)

1.6666666666666667


In [42]:
##Memanggil fungsi waktu_tempuh dengan parameters (100, 60)
waktu_tempuh(100, 60)

1.6666666666666667

In [36]:
a_44 = waktu_sampai(100, 60)
print(a_44)

1.6666666666666667
None


Outputnya terdapat none karena pada a_44 digunakan fungsi waktu_sampai, dimana fungsi tersebut tidak terdapat pengembalian nilai. Hanya menjalankan perintah dan menampilkan saja. Sehingga fungsi tidak dapat diolah kembali dan menghasilkan none.

In [37]:
b_44 = waktu_tempuh(100, 60)
print(b_44)

1.6666666666666667


Disini output tetap sama dengan output dari waktu_tempuh, hal itu dikarenakan fungsi waktu_tempuh terdapat return yang digunakan untuk mengembalikan suatu nilai, sehingga nilai tersebut bisa diolah kembali dengan menggunakan operasi atau disimpan dalam variabel yang berbeda.

Berdasarkan program di atas terdapat 2 jenis fungsi, yaitu fungsi tanpa pengembalian nilai dan fungsi dengan pengembalian nilai. Fungsi tanpa pengembalian nilai tidak dapat diolah kembali, sedangkan fungsi dengan pengembalian nilai bisa diolah kembali untuk berbagai kebutuhan.

### Contoh 2

In [43]:
##Numpy(Numerical Python) adalah sebuah library dalam python
import numpy as np 

In [44]:
##Mendeklarasikan fungsi
def luas_segitiga(alas_44, tinggi_44):
    luas_44 = (1/2) * alas_44 * tinggi_44
    return luas_44

In [51]:
##Mendeklarasikan fungsi
def luas_lingkaran(jari_jari_44):
    luas_44 = np.pi * (jari_jari_44 ** 2)
    return luas_44

In [52]:
##Mendeklarasikan fungsi
def luas_persegi(sisi_44):
    luas_44 = sisi_44 ** 2
    return luas_44

In [53]:
##Mendeklarasikan fungsi
def luas_persegi_panjang(panjang_44, lebar_44):
    luas_44 = panjang_44 * lebar_44
    return luas_44

In [48]:
jenis_bidang_44 = input('Tulis jenis bidangnya ')
if jenis_bidang_44.upper() == 'SEGITIGA':
    alas_44 = float(input('Berapa panjang alasnya? '))
    tinggi_44 = float(input('Berapa tingginya? '))
    luas_44 = luas_segitiga(alas_44, tinggi_44)
    print(f'Luas {jenis_bidang_44} adalah {luas_44}')
elif jenis.bidang_44.upper() == 'LINGKARAN':
    jari_jari_44 = float(input('Berapa panjang jari-jarinya? '))
    luas_44 = luas_lingkaran(jari_jari_44)
    print(f'Luas {jenis_bidang_44} adalah {luas_44}')
elif (jenis_bidang_44.upper() == 'PERSEGI') or (jenis_bidang_44.upper() == 'BUJUR SANGKAR'):
    sisi_44 = float(input('Berapa panjang sisinya? '))
    luas_44 = luas_persegi(sisi_44)
    print(f'Luas {jenis_bidang_44} adalah {luas_44}')
elif jenis_bidang_44.upper() == 'PERSEGI PANJANG':
    panjang_44 = float(input('Berapa panjangnya? '))
    lebar_44 = float(input('Berapa lebarnya? '))
    luas_44 = luas_persegi_panjang(panjang_44, lebar_44)
    print(f'Luas {jenis_bidang_44} adalah {luas_44}')
else:
    print(f'Maaf bidang {jenis_bidang_44} yang anda masukkan tidak ada.')
    print('Pilihannya hanya SEGITIGA, LINGKARAN, PERSEGI, dan PERSEGI PANJANG.')
    print('Terima kasih')

Tulis jenis bidangnya segitiga
Berapa panjang alasnya? 3
Berapa tingginya? 6
Luas segitiga adalah 9.0


Pada program di atas dibuat 4 fungsi luas untuk menentukan luas dari suatu bidang. Digunakan if dalam python untuk menentukan bidang apa yang diinputkan oleh pengguna. Sehingga yang terproses oleh komputer adalah bidang yang ada dalam pilihan. Apabila bidang yang diinputkan tidak ada, maka akan langsung menuju else terakhir.

# 5.20 Numpy

Numpy (Numerical Python) adalah salah satu library yang digunakan di Python. Numpy memiliki keunggulan dari segi penggunaan/pemakaian memory yang lebih kecil dan runtime yang lebih cepat dibandingkan yang lainnya.

In [55]:
##Mendeklarasikan numpy -> np, agar mempersingkat penggunaan kode
import numpy as np

## 5.20.1 Perintah Dasar pada Numpy

### Menampilkan Numpy menggunakan array

In [57]:
##Deklarasikan a sebagai numpy dengan array [0,1,2,3,4]
a_44 = np.array([0, 1, 2, 3, 4])

##Menampilkan a_44
print(a_44)

[0 1 2 3 4]


In [59]:
##Deklarasikan b sebagai numpy dengan array 2 dimensi
b_44 = np.array([[5, 6, 7, 8], [9, 8, 7, 6]])
print(b_44)

[[5 6 7 8]
 [9 8 7 6]]


In [60]:
####Deklarasikan c sebagai numpy dengan array dimensi
c_44 = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                 [[8, 9, 8, 7], [6, 5, 4, 3]],
                 [[1, 2, 3, 4], [5, 6, 7, 8]]
])
print(c_44)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


### Menentukan/Melihat Dimensi pada Numpy

In [61]:
a_44.ndim         ##nama_variabel.ndim

1

Berarti numpy di atas merupakan numpy dengan dimensi tunggal.

In [62]:
b_44.ndim         ##nama_variabel.ndim

2

Berarti numpy di atas merupakan numpy multi-dimensi yang berdimensi 2.

In [63]:
c_44.ndim         ##nama_variabel.ndim

3

Berarti numpy di atas merupakan numpy multi-dimensi yang berdimensi 3.

### Melihat Ukuran Numpy

In [64]:
a_44.shape        ##nama_variabel.shape

(5,)

Berarti numpy di atas merupakan numpy 1 dimensi yang berukuran 5.

In [65]:
b_44.shape        ##nama_variabel.shape

(2, 4)

Berarti numpy di atas berdimensi 2 dan memiliki ukuran dengan barisnya 2 dan kolomnya 4.

In [66]:
c_44.shape        ##nama_variabel.shape

(3, 2, 4)

Berarti numpy di atas berdimensi 3 dan memiliki ukuran dengan barisnya 2 dan kolomnya 4.

### Mengubah Ulang Ukuran Numpy

In [69]:
b_44 = b_44.reshape (4, 2)         ##nama_variabel = nama_variabel.reshape(baris, kolom)
print(b_44)

[[5 6]
 [7 8]
 [9 8]
 [7 6]]


Kode di atas digunakan untuk mengubah atau membentuk kembali numpy. Pada cotoh di atas, akan dibentuk kembali dari yang awalnya (2, 4) menjadi (4, 2). Yang berarti mengubah baris menjadi kolom, dan kolom menjadi baris.

## 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [70]:
##Mendeklarasikan d_44 sebagai numpy dengan menggunakan array
d_44 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d_44)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [72]:
##Memanggil anggota
d_44[0, 3]            ##nama_variabel[baris, kolom]

4

Berarti memanggil data dari d_44 dengan baris index ke-0 dan kolom index ke 3.

In [74]:
##Memanggil anggota
d_44[1, :]           ##nama_variabel[baris, kolom]

array([5, 6, 7, 8])

Berarti memanggil array dengan baris index ke 1 dan kolom yang tidak diketahui. Maka akan muncul semua anggota pada baris dengan index ke 1 tanpa memandang kolomnya.

In [75]:
d_44[:,2]            ##nama_variabel[baris, kolom]

array([ 3,  7, 11])

Berarti memanggil array dengan baris yang tidak diketahui dan kolom dengan index ke 2. Sehingga yang muncul adalah anggota dari kolom dengan index ke 2 saja.

In [76]:
d_44[0,1:3]          ##nama_variabel[baris, kolom]

array([2, 3])

Berarti memanggil baris dengan index ke-0, dan kolom dengan index ke 1 sampai ke 3 (tidak termasuk kolom ke-3, hanya 1 dan 2 saja).

In [77]:
d_44[0,0:3:2]       ##nama_variabel[baris, kolom]

array([1, 3])

Berarti memanggil baris dengan index ke-0 dan kolom dengan index ke-0 sampai kolom dengan index ke-3 dengan interval 2.

In [79]:
d_44[0,0] = 100     ##nama_variabel[baris, kolom] = data_baru
print(d_44)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


Program di atas digunakan untuk mengganti/mengubah nilai dari variabel d_44 dengan baris index ke 0 dan kolom index ke 0, dimana data awalnya adalah 1, lalu diubah menjadi 100.

## 5.20.3 Matrix pada Numpy

In [80]:
np.ones((2, 3))               ##np.ones((baris, kolom))

array([[1., 1., 1.],
       [1., 1., 1.]])

Kode di atas digunakan untuk membuat matriks dengan ordo 2*3 yang elemen keseluruhannya adalah 1.

In [81]:
np.zeros((3, 2))             ##np.zeros((baris, kolom))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Kode di atas digunakan untuk membuat matriks dengan ordo 3*2 yang elemen keseluruhannya adalah 0.

In [82]:
np.identity(4)               ##np.identity(ukuran matriks)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Kode di atas digunakan untuk membuat matriks identitas yang berordo 4*4.

In [83]:
np.ones((2, 3, 4))          

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Kode di atas digunakan untuk membuat matriks 2 dimensi dengan ordo 3*4 yang elemen keseluruhannya adalah 1.

In [84]:
np.full((3, 2), 9)

array([[9, 9],
       [9, 9],
       [9, 9]])

Kode di atas digunakan untuk membuat matriks ordo 3*2 yang elemen keseluruhannya 9.

In [85]:
np.random.rand(4, 3)          ##np.random.rand(baris, kolom)

array([[0.44009919, 0.37550493, 0.55623563],
       [0.66910005, 0.69937457, 0.12667686],
       [0.32909197, 0.42846801, 0.06496061],
       [0.72888585, 0.84050828, 0.39791653]])

Kode di atas digunakan untuk membuat matriks ordo 4*3 dengan elemen acak yang berupa float.

In [86]:
np.random.randint(1, 10, size=(3, 4))

array([[8, 5, 1, 4],
       [3, 6, 7, 8],
       [1, 2, 5, 1]])

Kode di atas digunakan untuk membuat matriks ordo 3*4 yang elemennya diambil secara acak di interval 1 sampai 10 dan berupa integer.

### Contoh Program

In [87]:
##Membuat matriks ordo 10*10 dengan elemen keseluruhannya adalah 0
a_44 = np.zeros((10, 10))
print(a_44)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [88]:
##Membuat matriks identitas dengan ordo 10*10 
b_44 = np.identity(10)
print(b_44)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [89]:
##Mengalikan matriks b_44 dengan 9 dan ditampung dalam variabel c
c_44 = 9*b_44
print(c_44)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [90]:
##Membuat matriks ordo 8*8 dengan elemen keseluruhan = 1
d_44 = np.ones((8, 8))
print(d_44)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [91]:
##Membuat matriks identitas ordo 8*8 yang dikalikan dengan 8
e_44 = np.identity(8)*8
print(e_44)

[[8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8.]]


In [93]:
##Penjumlahan dua matriks yang datanya disimpan dalam variabel baru f_44
f_44 = d_44 + e_44
print(f_44)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [94]:
c_44[1:-1, 1:-1] = f_44
print(c_44)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


Kode di atas berarti mengganti matriks c dengan f pada baris index ke 1 sampai sebelum -1 dan pada kolom index ke 1 sampai sebelum index ke -1. Jadi yang berubah selain dari [1:-1, 1:-1].

In [95]:
##Membuat matriks identitas dengan ordo 6*6 yang dikalikan dengan 9
g_44 = np.identity(6)*9
print(g_44)

[[9. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 9.]]


In [96]:
c_44[2:-2, 2:-2] = g_44
print(c_44)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


Kode di atas berarti mengganti matriks c dengan g pada baris index ke 2 sampai sebelum -2 dan pada kolom index ke 2 sampai sebelum index ke -2. Jadi yang berubah selain dari [2:-2, 2:-2].

In [97]:
##Membuat matriks dengan ordo 4*4 yang elemen keseluruhannya adalah 1, lalu matriks tersebut dikalikan dengan 2
h_44 = np.ones((4, 4))*2
print(h_44)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [98]:
##Membuat matriks identitas yang berordo 4*4 lalu dikalikan dengan 7
i_44 = np.identity(4)*7
print(i_44)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


In [99]:
##Penjumlahan 2 buah matriks yang hasilnya disimpan dalam variabel j_44
j_44 = h_44 + i_44
print(j_44)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [100]:
c_44[3:-3, 3:-3] = j_44
print(c_44)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


Kode di atas berarti mengganti matriks c dengan j pada baris index ke 3 sampai sebelum -3 dan pada kolom index ke 3 sampai sebelum index ke -3. Jadi yang berubah selain dari [3:-3, 3:-3].

In [101]:
##Membuat matriks identitas dengan ordo 2*2 yang dikalikan dengan 9
k_44 = np.identity(2)*9
print(k_44)

[[9. 0.]
 [0. 9.]]


In [102]:
c_44[4:-4, 4:-4] = k_44
print(c_44)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


Kode di atas berarti mengganti matriks c dengan k pada baris index ke 4 sampai sebelum -4 dan pada kolom index ke 4 sampai sebelum index ke -4. Jadi yang berubah selain dari [4:-4, 4:-4]

## 5.20.4 Copy pada Numpy

In [104]:
##Mendeklarasikan numpy dengan array
a_44 = np.array([1, 2, 3, 4, 5])
print(a_44)

[1 2 3 4 5]


In [105]:
##Mendeklarasikan b_44 = a_44
b_44 = a_44
print(b_44)

[1 2 3 4 5]


In [119]:
##Mengubah data pada index ke 0 menjadi 10
b_44[0] = 10
print(b_44)

[10  2  3  4  5]


In [120]:
##Data a berubah
print(a_44)

[10  2  3  4  5]


In [121]:
##Mendeklarasikan numpy dengan array
c_44 = np.array([1, 2, 3, 4, 5])
print(c_44)

[1 2 3 4 5]


In [122]:
##Mengcopy matriks c_44 yang disimpan di matriks d_44
d_44 = c_44.copy()
print(d_44)

[1 2 3 4 5]


In [123]:
##Mengubah matriks d_44 dengan index ke 0 menjadi 10
d_44[0] = 10
print(d_44)

[10  2  3  4  5]


In [124]:
##Menampilkan matriks c
print(c_44)

[1 2 3 4 5]


Dari program-program diatas, didapatkan kesimpulan bahwan apabila matriks di copy terlebih dahulu dan dilakukan perubahan pada datanya, maka tidak akan terjadi perubahan pada data aslinya. Namun jika hanya dideklarasikan sama saja, maka akan terjadi perubahan pada kedua matriks apabila salah satunya diubah datanya, karena sebelumnya sudah dideklarasikan apabila data 2 matriks tersebut sama.

## 5.20.5 Operasi Matematika pada Numpy

Kode di bawah ini digunakan untuk mengoperasikan matriks dengan bilangan secara langsung.

In [125]:
a_44 + 2

array([12,  4,  5,  6,  7])

In [126]:
a_44 - 2

array([8, 0, 1, 2, 3])

In [127]:
a_44 * 2

array([20,  4,  6,  8, 10])

In [128]:
a_44/2

array([5. , 1. , 1.5, 2. , 2.5])

In [129]:
a_44**2

array([100,   4,   9,  16,  25], dtype=int32)

Operasi dibawah ini digunakan untuk mengoperasikan dua buah matriks

In [130]:
b = np.array([6, 7, 8, 9, 10])
print(b)

[ 6  7  8  9 10]


In [131]:
a+b

array([ 6,  8, 10, 12, 14])

In [132]:
a-b

array([-6, -6, -6, -6, -6])

In [133]:
a*b

array([ 0,  7, 16, 27, 40])

In [134]:
a/b

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [135]:
b**a

array([    1,     7,    64,   729, 10000], dtype=int32)

In [136]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [137]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [139]:
np.sinh(a)

array([ 0.        ,  1.17520119,  3.62686041, 10.01787493, 27.2899172 ])

In [140]:
np.cosh(a)

array([ 1.        ,  1.54308063,  3.76219569, 10.067662  , 27.30823284])

In [142]:
np.tanh(a)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [145]:
##Digunakan untuk operasi pangkat
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

## 5.20.6 Perkalian Matriks pada Numpy

In [146]:
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [148]:
b=np.array([[9,10,11,12], [13, 14, 15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [149]:
c = a*b

In [151]:
d = np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

## 5.20.7 Min, Max, dan Sum pada Numpy

In [ ]:
a= p.array([[1, 2, 3, 4], [5, 6, 7, 8]])