File ini merupakan perbaikan dari Tugas V yang sebelumnya belum terselesaikan. Terima kasih.

In [3]:
import numpy as np

## 5.20.5 Operasi Matematika pada Numpy

Kode di bawah ini digunakan untuk mengoperasikan matriks dengan bilangan secara langsung.

### Operaris Penjumlahan pada Numpy

In [4]:
##Mendeklarasikan numpy dengan array
a_44 = np.array([1, 2, 3, 4, 5])
print(a_44)

[1 2 3 4 5]


In [5]:
##Melakukan penjumlahan numpy a_44 dengan 2, berarti semua data numpy a_44 dijumlahkan dengan 2
a_44 + 2

array([3, 4, 5, 6, 7])

### Operasi Pengurangan pada Numpy

In [6]:
##Melakukan pengurangan numpy a_44 dengan 2, berarti semua data numpy a_44 akan dikurangi dengan 2
a_44 - 2

array([-1,  0,  1,  2,  3])

### Operasi Perkalian pada Numpy

In [7]:
##Melakukan perkalian numpy a_44 dengan 2, berarti semua data numpy a_44 akan dikalikan dengan 2
a_44 * 2

array([ 2,  4,  6,  8, 10])

### Operasi Pembagian pada Numpy

In [8]:
##Melakukan pembagian numpy a_44 dengan 2, berarti semua data numpy a_44 akan dibagi dengan 2
a_44/2

array([0.5, 1. , 1.5, 2. , 2.5])

### Operasi Pemangkatan pada Numpy

In [9]:
##Melakukan pemangkatan numpy a_44 dengan pangkat 2, berarti semua data numpy a_44 akan dipangkatkan 2
a_44**2

array([ 1,  4,  9, 16, 25], dtype=int32)

Pada operasi di atas, terdapat dtype=int32 pada outputnya, hal itu menunjukkan bahwa nilai yang dikeluarkan bertipe data int.

Operasi dibawah ini digunakan untuk mengoperasikan dua buah matriks.

In [10]:
##Mendeklarasikan numpy dalam bentuk matriks
b_44 = np.array([6, 7, 8, 9, 10])
print(b_44)

[ 6  7  8  9 10]


In [11]:
##Operasi Penjumlahan, menjumlahkan numpy a_44 dengan b_44
a_44 + b_44

array([ 7,  9, 11, 13, 15])

In [12]:
##Operasi Pengurangan, mengurangi numpy a_44 dengan b_44
a_44 - b_44

array([-5, -5, -5, -5, -5])

In [13]:
##Operasi Perkalian, mengalikan numpy a_44 dengan b_44
a_44 * b_44

array([ 6, 14, 24, 36, 50])

In [14]:
##Operasi Pembagian, membagi numpy a_44 dengan b_44
a_44 / b_44

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
##Operasi Pemangkatan, numpy b_44 dipangkatkan dengan numpy  a_44
b_44 ** a_44

array([     6,     49,    512,   6561, 100000], dtype=int32)

### Operasi Trigonometri pada Numpy

In [19]:
##Untuk mencari nilai cos dari numpy a_44
np.cos(a_44)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [20]:
#Untuk mencari nilai sin dari numpy a_44
np.sin(a_44)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [21]:
#Untuk mencari nilai tangen dari numpy a_44
np.tan(a_44)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [22]:
##Fungsi ini untuk mengembalikan nilai sin hiperbolik dari nilainya
np.sinh(a_44)

array([ 1.17520119,  3.62686041, 10.01787493, 27.2899172 , 74.20321058])

In [23]:
##Fungsi ini untuk mengembalikan nilai cos hiperbolik dari nilainya
np.cosh(a_44)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284, 74.20994852])

In [24]:
##Fungsi ini untuk mengembalikan nilai tan hiperbolik dari nilainya
np.tanh(a_44)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [25]:
##Digunakan untuk menentukan akar kuadrat berdasarkan elemen
np.sqrt(a_44)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

## 5.20.6 Perkalian Matriks pada Numpy

Perkalian dua buah matriks pada numpy dengan mengoperasikan baris dan kolomnya.

In [26]:
##Mendeklarasikan matriks a_44
a_44 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a_44)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
##Mendeklarasikan matriks b_44
b_44 = np.array([[9,10,11,12], [13, 14, 15,16]])
print(b_44)

[[ 9 10 11 12]
 [13 14 15 16]]


In [28]:
##Perkalian matriks a_44 dengan b_44 (mengalikan antar isi matriksnya) yang hasilnya disimpan dalam variabel c_44
c_44 = a_44 * b_44
print(c_44)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [29]:
##Fungsi Matmul digunakan untuk perkalian dua matriks
d_44 = np.matmul(a_44,b_44)
print(d_44)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

Kode di atas error karena matmul sendiri merupakan fungsi yang digunakan untuk perkalian dalam matriks. matriks a_44 dan matriks b_44 tidak bisa dikalikan karena jumlah baris yang akan dikalikan pada kolom tidak sesuai, sehingga program error.

In [30]:
##Mendeklarasikan matriks e_44
e_44 = np.array([[9,10], [11,12], [13,14], [15,16]])
print(e_44)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [31]:
##Perkalian dua matriks menggunakan fungsi matmul
f_44 = np.matmul(a_44,e_44)
print(f_44)

[[130 140]
 [322 348]]


In [32]:
##Mengalikan isi 2 matriks
g_44 = a_44 * e_44
print(g_44)

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

Kode di atas error karena ukuran matriks a_44 dan matriks e_44 tidak sama, sehingga tidak dapat mengalikan isi matriksnya.

## 5.20.7 Min, Max, dan Sum pada Numpy

Untuk mengetahui nilai terkecil, terbesar, dan penjumlahan dalam numpy dapat menggunakan perintah min, max, dan sum.

In [33]:
##Mendeklarasikan variabel numpy dalam bentuk matriks
a_44 = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
print(a_44)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Perintah Min dalam Numpy

Min digunakan untuk mengetahui nilai terkecil dari suatu data yang dipanggil.

In [34]:
##Menampilkan nilai min di a_44 yang ditampung dalam variabel b_44
b_44 = np.min(a_44)
print(b_44)

1


In [35]:
##Menampilkan nilai min di baris a_44 yang ditampung dalam variabel c_44
c_44 = np.min(a_44, axis = 0)
print(c_44)

[1 2 3 4]


In [36]:
##Menampilkan nilai min di kolom a_44 yang ditampung dalam variabel d_44
d_44 = np.min(a_44, axis = 1)
print(d_44)

[1 5 9]


### Perintah Max dalam Numpy

Max digunakan untuk mengetahui nilai terkecil dari suatu data yang dipanggil.

In [37]:
##Menampilkan nilai max di a_44 yang ditampung dalam variabel e_44
e_44 = np.max(a_44)
print(e_44)

12


In [38]:
##Menampilkan nilai max di baris a_44 yang ditampung dalam variabel f_44
f_44 = np.max(a_44, axis = 0)
print(f_44)

[ 9 10 11 12]


In [39]:
##Menampilkan nilai max di kolom a_44 yang ditampung dalam variabel g_44
g_44 = np.max(a_44, axis = 1)
print(g_44)

[ 4  8 12]


### Perintah Sum dalam Numpy

Sum digunakan untuk menjumlahkan nilai

In [40]:
##Menampilkan hasil penjumlahan matriks a_44 yang disimpan dalam variabel h_44
h_44 = np.sum(a_44)
print(h_44)

78


In [41]:
##Menampilkan hasil penjumlahan dari baris matriks a_44 yang disimpan dalam variabel h_44
h_44 = np.sum(a_44, axis = 0)
print(h_44)

[15 18 21 24]


In [42]:
##Menampilkan hasil penjumlahan dari kolom matriks a_44 yang disimpan dalam variabel i_44
i_44 = np.sum(a_44, axis = 1)
print(i_44)

[10 26 42]


Berdasarkan beberapa kode di atas, dapat disimpulkan jika axis = 0 berarti baris, dan axis = 1 berarti kolom. 